apiVersion: apps/v1
kind: Deployment
metadata:
  name: java-app-deployment
  namespace: java-app-ns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: java-app
  template:
    metadata:
      labels:
        app: java-app
    spec:
      containers:
        - name: java-app
          image: githubacr1.azurecr.io/github-aks-img:v1
          ports:
            - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: java-app-service
  namespace: java-app-ns
spec:
  selector:
    app: java-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer
